CREATE TABLE IF NOT EXISTS Drinks(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    flavour VARCHAR(255) NOT NULL,
    price INT,
    type VARCHAR(255) NOT NULL,
    mL INT NOT NULL,
    PRIMARY KEY (ID)
);